name: Bygg, publish og deploy
permissions:
  contents: "read"
  id-token: "write"
  packages: "write"
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  APP: medlemskap-oppslag-pdfgen
jobs:
  build-and-publish:
    name: Bygg, test og push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generer versjon og image navn
        run: |
          TIME=$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M)
          COMMIT=$(git rev-parse --short=8 HEAD)
          VERSION=$TIME-$COMMIT
          echo "IMAGE=docker.pkg.github.com/${GITHUB_REPOSITORY}/$APP:$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - run: echo $VERSION > VERSION.txt
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: medlemskap # required
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # required, but is defined as an organization variable
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # required, but is defined as an organization secret
      - name: Last opp VERSION til neste job
        uses: actions/upload-artifact@v4
        with:
          name: VERSION.txt
          path: VERSION.txt
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build -t ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
    outputs:
      image: ${{ steps.docker-push.outputs.image }}

  deploy-to-dev-gcp:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/dev-')
    name: Deploy til dev-gcp (Q1)
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/naiserator.yaml
          VARS: nais/dev-gcp.json
          IMAGE: ${{ needs.build-and-publish.outputs.image }}
          TELEMETRY: ${{ needs.build-and-publish.outputs.telemetry }}

  deploy-to-prod-gcp:
    if: github.ref == 'refs/heads/main'
    name: Deploy til prod-gcp (Produksjon)
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: nais/naiserator.yaml
          VARS: nais/prod-gcp.json
          IMAGE: ${{ needs.build-and-publish.outputs.image }}
          TELEMETRY: ${{ needs.build-and-publish.outputs.telemetry }}